### ISSUE TITLE
设置亮色主题后，重启之后又变回黑色

### ISSUE THREAD

**Issue by JTFA** [BetterNCM/ThemeSwitcher#2]
今天更新之后设置亮色主题的情况下重启之后又会变成黑色主题（已关闭跟随系统）

**Comment by FeiLingshu** [comment]
### 造成这点的原因应该是作者没有考虑前台HTML元素初始化时的动作

> 我调试了一下插件，发现插件文件树中 ` main.js ` 文件第80行和第81行的代码有问题
> 第80行作者添加了一个计时器用来循环响应点击WYY皮肤按钮的事件，然后替换成自己的响应处理函数，循环频率1000ms
> 第81行作者估计是为了加快初始化响应速度（我估计，因为通过 ` setInterval ` 函数添加计时器，第一次触发之前需要等待一个完整的循环频率），手动触发了一次相关函数

这个函数里有一步重载了WYY换肤按钮的 ` onclick ` 事件，但是我之前自己没事瞎写别的事件的时候发现一个问题，就是所有 ` button ` 类的HTML元素在初始化自己的时候都会触发一次 ` onclick ` 事件，由于BNCM的加载事件（即 ` plugin.onLoad ` ）发生在HTML初始化之前，所以导致即使用户没有点击换肤按钮，插件也会自动换肤一次

[目前的办法就是直接注释掉第81行的代码，对功能几乎没有影响 —— （别点，找URL借个高亮而已）]()

- 所有猜想已通过添加 ` alert ` 函数调试验证

****

### 目前还有一个小问题解释不了：

插件文件中声明了一个值 ` localStorage['cc.microblock.themeswitcher.theme'] ` 用于保存用户配置

调试过程中（调试期间保留了第81行代码），每次重新启动WYY的时候确实都观测到值被改变一次（仅启动时发生一次），但是不知道什么原因，当值从 ` light ` 被更改成 ` dark ` 的时候，字体颜色会从黑色变成白色，但是当值从 ` dark ` 被更改成 ` light ` 的时候，字体颜色并不会从白色变成黑色（但通过 ` alert ` 函数打印当前值确实证实值被更改了）

### @MicroCBer
